desired_roll:         0.0 # [rad]
desired_pitch:        0.0 # [rad]
desired_yaw:          0.0 # [rad]
desired_thrust_force: 0.2 # [N], additional to gravity compensation

kx_1_value:     10.0
kx_2_value:     10.0
kx_3_value:     10.0

kx_1_dot_value: 8.0
kx_2_dot_value: 8.0
kx_3_dot_value: 8.0

kq_1_value:     9.0
kq_2_value:     9.0
kq_3_value:     9.0

kq_1_dot_value: 0.5
kq_2_dot_value: 0.5
kq_3_dot_value: 0.5

# rates of timers in Hz
rate:
  publish_quad_state:           100   # [Hz]
  publish_desired_quad_state:   100   # [Hz]
  publish_cable_state:          100   # [Hz]
  publish_desired_cable_state:  100   # [Hz]