desired_roll:         0.0 # [rad]
desired_pitch:        0.0 # [rad]
desired_yaw:          0.0 # [rad]
desired_thrust_force: 0.2 # [N], additional to gravity compensation

kx_1_value:     10.0
kx_1_dot_value: 8.0

kx_2_value:     10.0
kx_2_dot_value: 8.0

kx_3_value:     10.0
kx_3_dot_value: 8.0

# rates of timers in Hz
rate:
  publish_dist_to_waypoint: 1 # [Hz]
  publish_reference: 10 # [Hz]
  check_subscribers: 1 # [Hz]